# verbosity of logging (Trace, Debug, Warning, Info, Error, Fatal, Panic)
LogLevel = "Trace"

# configuration for the Onix Web API integration
[Onix]
    URL = "http://127.0.0.1:8080"
    AuthMode = "basic"
    Username = "admin"
    Password = "0n1x"
    ClientId = ""
    AppSecret = ""
    TokenURI = ""
    InsecureSkipVerify = true

# configuration for the Event broker integration
[Broker]
    Server = "tcp://127.0.0.1:1883"
    Username = ""
    Password = ""
    InsecureSkipVerify = true

# application to manage
[App]
    Key = ""
    CfgFile = ""
    ReloadCmd = ""
    ReloadURI = ""
    ReloadURIContentType = "text/plain"
    ReloadURIUser = ""
    ReloadURIPwd = ""
    ReadyURI = ""