info:
  contact:
    email: onix@gatblau.org
    name: Gatblau
    url: http://onix.gatblau.org/
  description: Call DbMan's commands using HTTP operations from anywhere.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  title: Onix DbMan
  version: 0.0.4
paths:
  /conf:
    get:
      description: Lists all variables in DbMan's configuration.
      produces:
      - text/plain
      responses:
        "200":
          description: OK
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Show DbMan's current configuration.
      tags:
      - Configuration
  /conf/check:
    get:
      description: Checks that the information in the current configuration set is ok to connect to backend services and the format of manifest is correct.
      produces:
      - text/plain
      responses:
        "200":
          description: OK
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Validates the current DbMan's configuration.
      tags:
      - Configuration
  /db/create:
    post:
      description: When the database does not already exists, this operation executes the manifest commands required to create the new database.
      produces:
      - text/plain
      responses:
        "200":
          description: OK
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Creates a new database
      tags:
      - Database
  /db/deploy:
    post:
      description: When the database is empty, this operation executes the manifest commands required to deploy the  database schema and objects.
      produces:
      - text/plain
      responses:
        "200":
          description: OK
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Deploys the schema and objects in an empty database.
      tags:
      - Database
  /db/info/queries:
    get:
      description: Lists all of the queries declared in the current release manifest.
      produces:
      - application/json
      - ' application/yaml'
      responses:
        "200":
          description: OK
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Gets a list of available queries.
      tags:
      - Database
  /db/info/server:
    get:
      description: Gets specific information about the database server to which DbMan is configured to connect.
      produces:
      - application/json
      - ' application/yaml'
      responses:
        "200":
          description: OK
          schema:
            type: json
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Retrieves database server information
      tags:
      - Database
  /db/query/{name}:
    get:
      description: Execute a query defined in the release manifest and return the result as a generic serializable table.
      parameters:
      - description: the name of the query as defined in the release manifest
        in: path
        name: name
        required: true
        type: string
      - description: a string of parameters to be passed to the query in the format 'key1=value1,...,keyN=valueN'
        in: query
        name: params
        type: string
      produces:
      - application/json
      - ' application/yaml'
      - ' application/xml'
      - ' text/csv'
      - ' text/html'
      - ' application/xhtml+xml'
      responses:
        "200":
          description: OK
          schema:
            type: Table
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Runs a query.
      tags:
      - Database
  /db/upgrade:
    post:
      description: This operation executes the manifest commands required to upgrade an existing database schema and objects to a new version. The target version is defined by DbMan's configuration value "AppVersion". This operation support rolling upgrades.
      produces:
      - text/plain
      responses:
        "200":
          description: OK
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Upgrade a database to a specific version.
      tags:
      - Database
  /ready:
    get:
      description: Checks that DbMan is ready to accept calls
      produces:
      - text/plain
      responses:
        "200":
          description: OK
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Check that DbMan is Ready
      tags:
      - General
swagger: "2.0"
